
CREATE TABLE `autos`.`pkw_offers` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`offer_uid` VARCHAR(30) NOT NULL ,
INDEX ( `offer_uid`),
`category_id` INT NOT NULL ,
`brand_id` INT NOT NULL,
`model_id` INT NULL,
`oiltypes_id` INT NOT NULL,
`manufacture_year` INT( 4 ) NOT NULL,
`geartype_id` INT NOT NULL,
`color_id` INT NOT NULL,
`country_id` INT NOT NULL,
`city_id` INT NULL DEFAULT NULL,
`status` INT NOT NULL,
`offer_status` INT NOT NULL,
`num_km` INT NOT NULL,
`price` INT NOT NULL,
`automatic_windshield` BOOLEAN NOT NULL DEFAULT '0',
`central_locks` BOOLEAN NOT NULL DEFAULT '0',
`leather_seats` BOOLEAN NOT NULL DEFAULT '0',
`airconditioner` BOOLEAN NOT NULL DEFAULT '0',
`navigator` BOOLEAN NOT NULL DEFAULT '0',
`power_steering` BOOLEAN NOT NULL DEFAULT '0',
`num_doors` SMALLINT( 2 ) NOT NULL DEFAULT '0',
`num_seats` SMALLINT( 2 ) NOT NULL DEFAULT '0',
`abs` BOOLEAN NOT NULL DEFAULT '0',
`fourx4` BOOLEAN NOT NULL DEFAULT '0',
`alarm` BOOLEAN NOT NULL DEFAULT '0',
`xenon` BOOLEAN NOT NULL DEFAULT '0',
`airbags` BOOLEAN NOT NULL DEFAULT '0',
`created` DATE NOT NULL,
`last_visited` DATE NOT NULL,
`hits` INT NOT NULL DEFAULT '0',
`description` VARCHAR( 10000 ) NULL
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE pkw_offers ADD CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES pkw_categories(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE pkw_offers ADD CONSTRAINT  fk_brand FOREIGN KEY (brand_id) REFERENCES pkw_brands(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE pkw_offers ADD CONSTRAINT  fk_model FOREIGN KEY (model_id) REFERENCES pkw_models(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE pkw_offers ADD CONSTRAINT  fk_oiltype FOREIGN KEY (oiltypes_id) REFERENCES oil_types(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE pkw_offers ADD CONSTRAINT  fk_geartype FOREIGN KEY (geartype_id) REFERENCES gear_type(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE pkw_offers ADD CONSTRAINT  fk_color FOREIGN KEY (color_id) REFERENCES colors(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE pkw_offers ADD CONSTRAINT  fk_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE CASCADE ON UPDATE CASCADE;
/*ALTER TABLE pkw_offers ADD CONSTRAINT  fk_city FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE CASCADE ON UPDATE CASCADE;*/
ALTER TABLE pkw_offers ADD CONSTRAINT  fk_status FOREIGN KEY (status) REFERENCES status(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE pkw_offers ADD CONSTRAINT  fk_offer_status FOREIGN KEY (offer_status) REFERENCES _offer_status(id) ON DELETE CASCADE ON UPDATE CASCADE;
