CREATE TABLE `autos`.`pkw_brands` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`en` VARCHAR( 50 ) NOT NULL ,
`ar` VARCHAR( 50 ) NOT NULL,
`de` VARCHAR( 50 ) NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci;
         
insert into pkw_brands (en,ar, de) values 
	 
('AC','أيه سى', 'AC'), 
('Audi','أودى', 'Audi'),
('Alfa Remeo','ألفا روميو', 'Alfa Remeo'),
('Alpina','ألبينا', 'Alpina'),
('Austin Rover','أوستين روفر', 'Austin Rover'),
('Austin Morris','أوستين موريس', 'Austin Morris'),
('Aston Martin','أستون مارتين', 'Aston Martin'),
('BMW','بى ام دبليو', 'BMW'),
('Buick','بويك', 'Buick'),
('Bentley','بنتلى', 'Bentley'),
('Bugatti','بوجاتى', 'Bugatti'),
('Cadillac','كاديلاك', 'Cadillac'),
('Chevrolet','شيفروليه', 'Chevrolet'),
('Chrysler','كريسلر', 'Chrysler'),
('Citroen','سيتروين', 'Citroen'),
('Cobra','كوبرا', 'Cobra'),
('Daewoo','دايوو', 'Daewoo'),
('Dodge','دودج', 'Dodge'),
('Dacia','داشيا', 'Dacia'),
('Daihatsu','دايهانسو', 'Daihatsu'),
('De Tomaso','دى توماسو', 'De Tomaso'),
('Ford','فورد', 'Ford'),
('Ferrari','فيرارى', 'Ferrari'),
('Fiat','فيات', 'Fiat'),
('GMC','جى ام سى', 'GMC'),
('Honda','هوندا', 'Honda'),
('Hyundai','هيونداى', 'Hyundai'),
('Hummer','هامر', 'Hummer'),
('Infiniti','اينفينيتى', 'Infiniti'),
('Isuzu','ايسوزو', 'Isuzu'),
('Innocenti','اينوسينتى', 'Innocenti'),
('Jagaur','جاجوار', 'Jagaur'),
('Jeep','جييب', 'Jeep'),
('Kia','كيا', 'Kia'),
('Lada','لادا', 'Lada'),
('Land  Rover','لاند روفر', 'Land  Rover'),
('Lancia','لانسيا', 'Lancia'),
('Ligier','ليجير', 'Ligier'),
('Lotus','لوتس', 'Lotus'),
('Lexus','ليكسيس', 'Lexus'),
('Lincoln','لينكولن', 'Lincoln'),
('Lamborghini','لامبورجينى', 'Lamborghini'),
('Mazda','مازدا', 'Mazda'),
('Mercedes-Benz','مرسيدس', 'Mercedes-Benz'),
('Mercury','ميركورى', 'Mercury'),
('Mini','مينى', 'Mini'),
('Mitsubishi','ميتسوبيشى', 'Mitsubishi'),
('Mahindra','ماهيندرا', 'Mahindra'),
('Maserati','ماسيراتى', 'Maserati'),
('Maybach','ماى باخ', 'Maybach'),
('MG','ام جى', 'MG'),
('Morgan','مورجن', 'Morgan'),
('Nissan','نيسان', 'Nissan'),
('Oldsmobile','اولدس موبيل', 'Oldsmobile'),
('Opel','اوبل', 'Opel'),
('Oldtimer','اولد تيمر', 'Oldtimer'),
('Peugeot','بيجوت', 'Peugeot'),
('Pontiac','بونتياك', 'Pontiac'),
('Porsche','بورش', 'Porsche'),
('Piaggio','بياجيو', 'Piaggio'),
('Plymouth','بلىموث', 'Plymouth'),
('Proton','بروتون', 'Proton'),
('Renault','رينوه', 'Renault'),
('Rolls Royce','رولس رويس', 'Rolls Royce'),
('Rover','روفر', 'Rover'),
('Saab','ساب', 'Saab'),
('Seat','سيات', 'Seat'),
('Skoda','سكودا', 'Skoda'),
('Smart','سمارت', 'Smart'),
('Satum','ساتوم', 'Satum'),
('Scion','سكيون', 'Scion'),
('Subaru','سوبارو', 'Subaru'),
('Ssang Yong','سانج يونج', 'Ssang Yong'),
('Santana','سانتانا', 'Santana'),
('Suzuki','سوزوكى', 'Suzuki'),
('Toyota','تويوتا', 'Toyota'),
('Talbot','تالبوت', 'Talbot'),
('Trabant','ترابانت', 'Trabant'),
('Triumph','تريومف', 'Triumph'),
('TVR','تى فى ار', 'TVR'),
('Volkswagen','فولكس واجن', 'Volkswagen'),
('Volvo','فولفو', 'Volvo'),
('Vauxhall','فاوكس هال', 'Vauxhall'),
('Wartburg','فارت بورج', 'Wartburg'),
('Wiesmann','فيس مان', 'Wiesmann')
;